### ISSUE TITLE
Investigate installer efi "--docker-image" test

### ISSUE THREAD

**Issue by Itxaka** [rancher/elemental-toolkit#1079]
**cos-toolkit version:**
master

**CPU architecture, OS, and Version:**

**Describe the bug**
Seems like lately the installer efi --docker-iamge test is timing out for no apparent reason. It could be that the image is bigger and that mixed with the general slowness of the efi installer tests results in a timeout, or there may be another reason for it. 

Still would be good to know why is it failing and if we can workaround it somehow, as to not waste almost 1 hour in a test path that keeps failing.

**To Reproduce**

**Expected behavior**

**Logs**

**Additional context**

**Comment by Itxaka** [comment]
Forcing GPT also usually fails lately.

**Comment by davidcassany** [comment]
Just for the records on #1074 I am also seeing non consistent failures in installer tests due to connection timeouts. Specially it happens quite often for EFI setups on reboot after restoring the cOS ISO to the VM. I have not noted a relation between the use of `force-gpt` or use of `docker-imge`, I have seen them pass and fail as other EFI tests, always on reboot during AfterEach, so the test essentially passes, it is on the cleanup restore phases that it timeouts.

**Comment by davidcassany** [comment]
Just verified in #1074 that increasing the timeout helps, but still fails time to time... Looks like VirtualBox is not that stable for EFI...

Now I got a [failure](https://github.com/rancher-sandbox/cOS-toolkit/runs/4968588256?check_suite_focus=true) while restoring the CD with:
```
VBoxManage: error: Invalid state 'GURU_MEDITATION' for changing medium
make: *** [test-installer-efi] Error 1
VBoxManage: error: Details: code VBOX_E_INVALID_VM_STATE (0x80bb0002), component ConsoleWrap, interface IConsole, callee nsISupports
VBoxManage: error: Context: "MountMedium(Bstr(pszCtl).raw(), port, device, pMedium2Mount, fForceUnmount)" at line 763 of file VBoxManageStorageController.cpp
```

Knowing that VBoxManage has a `GURU_MEDITATION` state doesn't make me feel better 😅

**Comment by frelon** [comment]
Installer tests are removed, closing this
