### ISSUE TITLE
immutable-rootfs: Bind mounts not mounting after #1364

### ISSUE THREAD

**Issue by kcburge** [rancher/elemental-toolkit#1475]
**Is your feature request related to a problem? Please describe.**

I am using the following configuration, with bind mounts.
       
    - name: Persistent state
      if: '[ ! -f "/run/cos/recovery_mode" ]'
      environment_file: /run/cos/cos-layout.env
      environment:
        VOLUMES: LABEL=COS_OEM:/oem LABEL=COS_PERSISTENT:/usr/local
        OVERLAY: tmpfs:25%
        RW_PATHS: /etc /srv /var
        PERSISTENT_STATE_PATHS: /etc/cni /etc/iscsi /etc/rancher /etc/ssh /etc/systemd /home /opt /root /usr/libexec /var/lib/cni /var/lib/kubelet /var/lib/longhorn /var/lib/rancher /var/lib/wicked /var/log
        PERSISTENT_STATE_BIND: "true"

immutable-rootfs-system-0.5-1 which incorporates the #1364 fix, doesn't mount any of my bind mounts for directories that don't exist.  I.e. /var/lib/rancher doesn't exist and so does not bind mount, it instead mounts with overlayfs.  Before the fix, it would create these bind mount directories.

There were no errors in the log indicating the fact that these would not or could not be bind mounted.

I am able to work around this problem by creating these directories in my docker image and adding .keep files.

UPDATE: I tried creating these directories via cloud-init, in both rootfs and rootfs.after, and neither worked.  It seems it must exist in the Docker image, which limits the flexibility of controlling this via PERSISTENT_STATE_PATHS.

**Describe the solution you'd like**
I would like it to create the bind mount directories, if they do not exist.

**Additional context**
#1364

**Comment by mudler** [comment]
Yes, thanks for raising this, it seems indeed there was a behavioral change, which also broke elemental tests: https://github.com/rancher/elemental/pull/134

**Comment by davidcassany** [comment]
Right, I had a closer look and the change we applied in #1364 was definitely too aggressive, I believe we did not properly understand what was going on in #1311, I'd say the failure reported there is pretty corner case in which missing directory can't be created, I naively though that this was a generic issue for all missing paths so that skipping missing directories would be enough.

@mudler probably do you remember which was the path raising the issue in #1311, my guess after a closer look is that the offending path should have been one that is not part of rootfs and not under an ephemeral path. 

I'll try to come with a PR to fix this. Also gonna explore if I can find some sane way to log what is happening that portion of the code.

**Comment by mudler** [comment]
If I remember this one correctly, in our case was `/usr/libexec`. which is mounted ro IIRC, so should match with your analysis indeed
