### ISSUE TITLE
Invalid check for ok

### ISSUE THREAD

**Issue by kcburge** [rancher/elemental-toolkit#1525]
I made a comment on the commit that introduced this, but wanted to make sure my message was not missed.  This appears to be an invalid comparison for an "ok" value, as indicated by the surrounding context.

https://github.com/rancher/elemental-toolkit/blob/e0ecf9ea0416e3beaa96d92a8c154eaaf86f7c92/packages/immutable-rootfs/30cos-immutable-rootfs/cos-loop-img.sh#L18

**Comment by fgiudici** [comment]
Hey @kcburge ,
thanks for reporting!
If you comment an already merged PR, yep, that comment may be missed.
In this case the comparison is valid: in bash string constants don't need to be quoted. Anyway, I see that at line 55 of the same file we have a similar comparison with "ok" quoted. So, while it would not change the functionality, I would make sense to keep the same style between the two.
Would you consider opening a PR? The fix is pretty quick, and we can do easily, but could be nice to have you as a contributor :-)

**Comment by davidcassany** [comment]
Damn it! Looks like I don't know how to code any more.... Once again did some stupid errors, yes the intention was to keep it quoted, thanks for pointing this out @kcburge. Luckly, as @fgiudici pointed, in this case makes no difference, but I completely agree this should be quoted.

We should probably start considering using `shellcheck` at build time to prevent this sort of errors and typos.

> could be nice to have you as a contributor :-)

I can't agree more

**Comment by kcburge** [comment]
@davidcassany Was laughing in disbelief this morning as I tried variations of unquoted strings in bash, all of which worked. You think you know a shell...then one day you discover you've been projecting other lesser "higher" languages on to them. :-)
