### ISSUE TITLE
Fix CI issues

### ISSUE THREAD

**Issue by mudler** [rancher/elemental-toolkit#1529]
Currently the CI is failing on two issues:
- https://github.com/rancher/elemental-toolkit/runs/6945594390?check_suite_focus=true (arm recovery test failing)
- drop uploading Odroid_c2 leap image on release. it fails as it exceed maximum image length

**Comment by Itxaka** [comment]
Arm recovery test fixed.

Problem was that the latest artifacts for arm64 were broken, so the test that upgraded to the latest was failing to boot after upgrading.

A PR was created that just skipped the tests part and only build and published artifacts: https://github.com/rancher/elemental-toolkit/pull/1522

an arm64 run for that PR was created (arm64 label in the PR) so after the latest fixed artifacts were pushed, the tests passed as expected.


Also regarding the odroid image, @frelon pushed a change, I cutted a release and the image was not uploaded, so that should also be fixed :)

**Comment by mudler** [comment]
indeed, seems we are just having issues with the runners now... I thought all deps were covered by the docker image? aren't we using that in the terraform templates @Itxaka ?

**Comment by Itxaka** [comment]
nope, terraform templates for arm64 are for VMs, like full VMs, not docker containers nor k8s. I fixed a couple of issues (python+python-yaml deps missing) but it should be good now.

**Comment by mudler** [comment]
This is done, let's tackle the remaining issues as #1555
