### ISSUE TITLE
Upgrade grub configuration

### ISSUE THREAD

**Issue by frelon** [rancher/elemental-toolkit#1840]
When running `elemental install` on a host the `grub.cfg` is extracted to the state partition and then never updated.

During upgrade we should extract the `grub.cfg` from the relevant image and update the configuration.

**Comment by davidcassany** [comment]
In fact this was a design choice. I have been doubtful about this since the very beginning.

The main reason is to ensure the fallback partition is still capable to boot after upgrading. Note that if grub setup changes there is no longer a previously known setup the fallback partition. Grub setup is a very sensitive piece in elemental-toolkit.

We tried to condense to the minimum expression what is required to be common across all images, that's also why grub reads a portion of the configuration from the loop device, as this is provided by the image so it can change from fallback to active.

Which is the change you required in grub? It is likely to point to some design issue somewhere (probably in our current setup).

**Comment by frelon** [comment]
> Which is the change you required in grub? It is likely to point to some design issue somewhere (probably in our current setup).

I was changing the `cos-img/filename` -> `elemental.image` in the mount command in #1837 and was checking how to make that backwards compatible in a somewhat easy way and come upon this.

Looking at the code again I saw that the config is actually overwritten during `reset` so we can upgrade the recovery image and then run a reset to actually update the configuration.

**Comment by frelon** [comment]
Closing this as wont fix, the workaround is to upgrade recovery image and then running reset after booting the recovery system.

**Comment by davidcassany** [comment]
> We probably have to change kernel parameters to accommodate to strange hardware ... 🤔

**Changing** is not possible nowadays, however appending arguments is actually possible. We used to have a very old issue without consensus close to this idea #1773. However since then we refactored a lot and moved to a way more flexible approach based on grub2 variables, so probably worth discussing how kernel parameters could be modified at install/runtime again.
